[package]
name = "risc0-smt"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "0.21", default-features = false, features = ["std"] }
serde = "1.0"

[dev-dependencies]
serde_json = "1.0"
